name: memory
description: "Your Daily Notes"

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6
  icons_launcher: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.6
  hive_generator: ^2.0.1

icons_launcher:
  image_path: "assets/images/png_images/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  image: "assets/images/png_images/splash_icon.png"
  color: "#ffffff"
  android_12:
    image: "assets/images/png_images/splash_icon.png"
    color: "#ffffff"
  android: true
  ios: true
  web: false
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/
